version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - bourbon-bundle-v1-{{ checksum "bourbon.gemspec" }}
            - bourbon-bundle-v1-
      - run:
          name: Run Bundler
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bourbon-bundle-v1-{{ checksum "bourbon.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Run the tests
          command: bundle exec rake
      - run:
          name: Parse SassDoc comments
          command: npm run sassdoc
